# “Chemical Compound Formula | Formula Chart,” BYJUS, Nov. 03, 2018. https://byjus.com/chemical-compound-formulas/ (accessed Dec. 23, 2023).
general = [
    {"name": "Acetic acid", "formula": "CH3COOH"},
    {"name": "Hydrochloric acid", "formula": "HCl"},
    {"name": "Sulfuric acid", "formula": "H2SO4"},
    {"name": "Acetate", "formula": "CH3COO–"},
    {"name": "Ammonia", "formula": "NH3"},
    {"name": "Nitric acid", "formula": "HNO3"},
    {"name": "Phosphoric acid", "formula": "H3PO4"},
    {"name": "Sodium phosphate", "formula": "Na3PO4"},
    {"name": "Calcium carbonate", "formula": "CaCO3"},
    {"name": "Ammonium sulfate", "formula": "(NH4)2SO4"},
    {"name": "Carbonic acid", "formula": "H2CO3"},
    {"name": "Sodium bicarbonate", "formula": "NaHCO3"},
    {"name": "Sodium hydroxide", "formula": "NaOH"},
    {"name": "Calcium hydroxide", "formula": "Ca(OH)2"},
    {"name": "Ethanol", "formula": "C2H5OH"},
    {"name": "Hydrobromic acid", "formula": "HBr"},
    {"name": "Nitrous acid", "formula": "HNO2"},
    {"name": "Potassium hydroxide", "formula": "KOH"},
    {"name": "Silver nitrate", "formula": "AgNO3"},
    {"name": "Sodium carbonate", "formula": "Na2CO3"},
    {"name": "Sodium chloride", "formula": "NaCl"},
    {"name": "Cellulose", "formula": "(C6H10O5)n"},
    {"name": "Magnesium hydroxide", "formula": "Mg(OH)2"},
    {"name": "Methane", "formula": "CH4"},
    {"name": "Nitrogen dioxide", "formula": "NO2"},
    {"name": "Sodium nitrate", "formula": "NaNO3"},
    {"name": "Sulfurous acid", "formula": "H2SO3"},
    {"name": "Aluminium sulfate", "formula": "Al2(SO4)3"},
    {"name": "Aluminum oxide", "formula": "Al2O3"},
    {"name": "Ammonium nitrate", "formula": "NH4NO3"},
    {"name": "Ammonium phosphate", "formula": "(NH4)3PO4"},
    {"name": "Barium hydroxide", "formula": "Ba(OH)2"},
    {"name": "Carbon tetrachloride", "formula": "CCl4"},
    {"name": "Citric acid", "formula": "C6H8O7"},
    {"name": "Hydrocyanic acid", "formula": "HCN"},
    {"name": "Salicylic Acid", "formula": "C7H6O3"},
    {"name": "Hydroiodic acid", "formula": "HI"},
    {"name": "Hypochlorous acid", "formula": "HClO"},
    {"name": "Iron iii oxide", "formula": "Fe2O3"},
    {"name": "Magnesium phosphate", "formula": "Mg3(PO4)2"},
    {"name": "Sodium acetate", "formula": "C2H3NaO2"},
    {"name": "Sodium sulfate", "formula": "Na2SO4"},
    {"name": "Sucrose", "formula": "C12H22O11"},
    {"name": "Potassium nitrate", "formula": "KNO3"},
    {"name": "Ammonium bicarbonate", "formula": "NH4HCO3"},
    {"name": "Ammonium chloride", "formula": "NH4Cl"},
    {"name": "Ammonium hydroxide", "formula": "NH4OH"},
    {"name": "Calcium nitrate", "formula": "Ca(NO3)2"},
    {"name": "Calcium oxide", "formula": "CaO"},
    {"name": "Carbon monoxide", "formula": "CO"},
    {"name": "Chlorine gas", "formula": "Cl2"},
    {"name": "Phenol", "formula": "C6H6O"},
    {"name": "Hydrogen peroxide", "formula": "H2O2"},
    {"name": "Hydroxide", "formula": "OH–"},
    {"name": "Magnesium chloride", "formula": "MgCl2"},
    {"name": "Potassium chloride", "formula": "KCl"},
    {"name": "Potassium iodide", "formula": "KI"},
    {"name": "Sulfur dioxide", "formula": "SO2"},
    {"name": "Glycerin", "formula": "C3H8O3"},
    {"name": "Barium nitrate", "formula": "Ba(NO3)2"},
    {"name": "Calcium acetate", "formula": "C4H6O4Ca"},
    {"name": "Iron oxide", "formula": "Fe2O3"},
    {"name": "Potassium carbonate", "formula": "K2CO3"},
    {"name": "Silver chloride", "formula": "AgCl"},
    {"name": "Sodium iodide", "formula": "NaI"},
    {"name": "Sodium oxide", "formula": "Na2O"},
    {"name": "Sodium sulfide", "formula": "Na2S"},
    {"name": "Zinc nitrate", "formula": "Zn(NO3)2"},
    {"name": "Phenolphthalein", "formula": "C20H14O4"},
    {"name": "Magnesium nitrate", "formula": "Mg(NO3)2"},
    {"name": "Silicon dioxide", "formula": "SiO2"},
    {"name": "Acetone", "formula": "C3H6O"},
    {"name": "Hydroquinone", "formula": "C6H6O2"},
    {"name": "Pyridine", "formula": "C5H5N"},
    {"name": "Ammonium acetate", "formula": "C2H3O2NH4"},
    {"name": "Xylene", "formula": "C8H10"},
    {"name": "Barium sulfate", "formula": "BaSO4"},
    {"name": "Benzene", "formula": "C6H6"},
    {"name": "Bicarbonate", "formula": "CHO3–"},
    {"name": "Chromate", "formula": "CrO42-"},
    {"name": "Methyl Ethyl Ketone", "formula": "C4H8O"},
    {"name": "Cyanide", "formula": "CN−"},
    {"name": "Trichloroacetic acid", "formula": "C2HCl3O2"},
    {"name": "Magnesium sulfate", "formula": "MgSO4"},
    {"name": "Methanol", "formula": "CH3OH"},
    {"name": "Oxygen", "formula": "O"},
    {"name": "Methylene blue", "formula": "C16H18ClN3S"},
    {"name": "Sodium sulfite", "formula": "Na2SO3"},
    {"name": "Sulfur trioxide", "formula": "SO3"},
    {"name": "Aluminum phosphate", "formula": "AlPO4"},
    {"name": "Stearic acid", "formula": "C18H36O2"},
    {"name": "Dinitrogen monoxide", "formula": "N2O"},
    {"name": "Titanium dioxide", "formula": "TiO2"},
    {"name": "Acetonitrile", "formula": "C2H3N"},
    {"name": "Oxalic acid", "formula": "H2C2O4"},
    {"name": "Potassium dichromate", "formula": "K2Cr2O7"},
    {"name": "Sodium bromide", "formula": "NaBr"},
    {"name": "Sodium hypochlorite", "formula": "NaClO"},
    {"name": "Zinc acetate", "formula": "Zn(CH3COO)2(H2O)2"},
    {"name": "Zinc chloride", "formula": "ZnCl2"},
    {"name": "Zinc hydroxide", "formula": "Zn(OH)2"},
    {"name": "Magnesium carbonate", "formula": "MgCO3"},
    {"name": "Potassium chlorate", "formula": "KClO3"},
    {"name": "Hydrazine", "formula": "N2H4"},
    {"name": "Ascorbic acid", "formula": "C6H8O6"},
    {"name": "Benzoic acid", "formula": "C7H6O2"},
    {"name": "Resorcinol", "formula": "C6H6O2"},
    {"name": "Chlorine", "formula": "Cl2"},
    {"name": "Maleic acid", "formula": "C4H4O4"},
    {"name": "Sodium metabisulfite", "formula": "Na2S2O5"},
    {"name": "Acetamide", "formula": "C2H5NO"},
    {"name": "Sodium silicate", "formula": "(Na2O)x·SiO2"},
    {"name": "Nitrite", "formula": "NO2−"},
    {"name": "Phosphate", "formula": "PO43-"},
    {"name": "Dichloromethane", "formula": "CH2Cl2"},
    {"name": "Carbon Disulfide", "formula": "CS2"},
    {"name": "Potassium chromate", "formula": "CrK2O4"},
    {"name": "Zinc sulfate", "formula": "ZnSO4"},
    {"name": "Iodine", "formula": "I"},
    {"name": "Tannic acid", "formula": "C76H52O46"},
    {"name": "Aluminum", "formula": "Al"},
    {"name": "Perchloric acid", "formula": "HClO4"},
    {"name": "Hypochlorite", "formula": "ClO–"},
    {"name": "Potassium Bromide", "formula": "KBr"},
    {"name": "Chromic acid", "formula": "H2CrO4"},
    {"name": "Dihydrogen monoxide", "formula": "OH2"},
    {"name": "Methyl acetate", "formula": "C3H6O2"},
    {"name": "Dimethyl sulfoxide", "formula": "C2H6OS"},
    {"name": "Hexane", "formula": "C6H14"},
    {"name": "Eugenol", "formula": "C10H12O2"},
    {"name": "Manganese dioxide", "formula": "MnO2"},
    {"name": "Lactic acid", "formula": "C3H6O3"},
    {"name": "Sodium potassium tartrate", "formula": "C4H4O6KNa·4H2O"},
    {"name": "Hexamine", "formula": "C6H12N4"},
    {"name": "Lithium hydroxide", "formula": "LiOH"},
    {"name": "Phosphorus pentachloride", "formula": "PCl5"},
    {"name": "Potassium oxide", "formula": "K2O"},
    {"name": "Monopotassium phosphate", "formula": "KH2PO4"},
    {"name": "Silver acetate", "formula": "AgC2H3O2"},
    {"name": "Sodium citrate", "formula": "Na3C6H5O7"},
    {"name": "Sodium fluoride", "formula": "NaF"},
    {"name": "Sodium nitrite", "formula": "NaNO2"},
    {"name": "Sulfate ion", "formula": "SO42−"},
    {"name": "Barium carbonate", "formula": "BaCO3"},
    {"name": "Calcium iodide", "formula": "CaI2"},
    {"name": "Hydrogen sulfate", "formula": "HSO4–"},
    {"name": "Lithium oxide", "formula": "Li2O"},
    {"name": "Dimethylglyoxime", "formula": "C4H8N2O2"},
    {"name": "Potassium Permanganate", "formula": "KMnO4"},
    {"name": "Silver phosphate", "formula": "Ag3PO4"},
    {"name": "Ammonium bromide", "formula": "NH4Br"},
    {"name": "Calcium phosphate", "formula": "Ca3(PO4)2"},
    {"name": "Dichromate", "formula": "K2Cr2O7"},
    {"name": "Aluminum sulfide", "formula": "Al2S3"},
    {"name": "Ammonium carbonate", "formula": "(NH4)2CO3"},
    {"name": "Barium chloride", "formula": "BaCl2"},
    {"name": "Nitrogen monoxide", "formula": "NO"},
    {"name": "Fructose", "formula": "C6H12O6"},
    {"name": "Magnesium iodide", "formula": "MgI2"},
    {"name": "Magnesium sulfide", "formula": "MgS"},
    {"name": "Ozone", "formula": "O3"},
    {"name": "Potassium cyanide", "formula": "KCN"},
    {"name": "Silver oxide", "formula": "Ag2O"},
    {"name": "Sodium chromate", "formula": "Na2CrO4"},
    {"name": "Sodium peroxide", "formula": "Na2O2"},
    {"name": "Toluene", "formula": "C7H8"},
    {"name": "Zinc carbonate", "formula": "ZnCO3"},
    {"name": "Zinc phosphate", "formula": "Zn3(PO4)2"},
    {"name": "Zinc sulfide", "formula": "ZnS"},
    {"name": "Para dichlorobenzene", "formula": "C6H4Cl2"},
    {"name": "Boric acid", "formula": "H3BO3"},
    {"name": "Oxalate", "formula": "C2O42−"},
    {"name": "Potassium bicarbonate", "formula": "KHCO3"},
    {"name": "Potassium hypochlorite", "formula": "KClO"},
    {"name": "Potassium nitrite", "formula": "KNO2"},
    {"name": "Bromothymol Blue", "formula": "C27H28Br2O5S"},
    {"name": "Ammonium iodide", "formula": "NH4I"},
    {"name": "Ammonium nitrite", "formula": "NH4NO2"},
    {"name": "Ammonium oxide", "formula": "(NH4)2O"},
    {"name": "Argon gas", "formula": "Ar"},
    {"name": "Barium bromide", "formula": "BaBr2"},
    {"name": "Barium iodide", "formula": "BaI2"},
    {"name": "Bromate", "formula": "BrO3–"},
    {"name": "Dinitrogen trioxide", "formula": "N2O3"},
    {"name": "Ethylene glycol", "formula": "C2H6O2"},
    {"name": "Nickel sulfate", "formula": "NiSO4"},
    {"name": "Helium", "formula": "He"},
    {"name": "Iodide", "formula": "I–"},
    {"name": "Lead ii acetate", "formula": "Pb(C2H3O2)2"},
    {"name": "Lithium chloride", "formula": "LiCl"},
    {"name": "Phosphate ion", "formula": "PO43-"},
    {"name": "Potassium fluoride", "formula": "KF"},
    {"name": "Potassium sulfite", "formula": "K2SO3"},
    {"name": "Silver carbonate", "formula": "Ag2CO3"},
    {"name": "Sodium cyanide", "formula": "NaCN"},
    {"name": "Sodium nitride", "formula": "Na3N"},
    {"name": "Strontium chloride", "formula": "SrCl2"},
    {"name": "Strontium nitrate", "formula": "Sr(NO3)2"},
    {"name": "Urea", "formula": "CH4N2O"},
    {"name": "Bleach", "formula": "NaClO"},
    {"name": "Lithium bromide", "formula": "LiBr"},
    {"name": "Aluminum fluoride", "formula": "AlF3"},
    {"name": "Barium fluoride", "formula": "BaF2"},
    {"name": "Butanoic acid", "formula": "C4H8O2"},
    {"name": "Calcium hydride", "formula": "CaH2"},
    {"name": "Copper ii carbonate", "formula": "CuCO3"},
    {"name": "Fluorine", "formula": "F"},
    {"name": "Lithium phosphate", "formula": "Li3PO4"},
    {"name": "Glycerol", "formula": "C3H8O3"},
    {"name": "Hypobromous acid", "formula": "HBrO"},
    {"name": "Hypoiodous acid", "formula": "HIO"},
    {"name": "Lead iodide", "formula": "PbI2"},
    {"name": "Lithium iodide", "formula": "LiI"},
    {"name": "Magnesium oxide", "formula": "MgO"},
    {"name": "Urethane", "formula": "C3H7NO2"},
    {"name": "Nickel nitrate", "formula": "Ni(NO3)2"},
    {"name": "Sodium dichromate", "formula": "Na2Cr2O7"},
    {"name": "Tartaric acid", "formula": "C4H6O6"},
    {"name": "Zinc iodide", "formula": "ZnI2"},
    {"name": "Bromine", "formula": "Br"},
    {"name": "Aluminum bromide", "formula": "AlBr3"},
    {"name": "Sodium Percarbonate", "formula": "C2H6Na4O12"},
    {"name": "Nickel acetate", "formula": "C4H6O4Ni"},
    {"name": "Sodium Thiosulfate", "formula": "Na2S2O3"},
    {"name": "Acetaldehyde", "formula": "C2H4O"},
    {"name": "Copper sulfate", "formula": "CuSO4"},
    {"name": "Mannitol", "formula": "C6H14O6"},
    {"name": "Calcium Chloride", "formula": "CaCl2"},
    {"name": "Monosodium Glutamate", "formula": "C5H8NO4Na"},
    {"name": "Polystyrene", "formula": "(C8H8)n"},
    {"name": "Calcium Carbide", "formula": "CaC2"},
    {"name": "Tetrachloroethylene", "formula": "C2Cl4"},
    {"name": "Sodium Chlorate", "formula": "NaClO3"},
    {"name": "Potassium Iodate", "formula": "KIO3"},
    {"name": "Lead Acetate", "formula": "Pb(C2H3O2)2"},
    {"name": "Potassium Thiocyanate", "formula": "KSCN"},
    {"name": "Butane", "formula": "C4H10"},
    {"name": "Maltose", "formula": "C12H22O11"},
    {"name": "Polyurethane Foam", "formula": "C27H36N2O10"},
    {"name": "Formaldehyde", "formula": "CH2O"},
    {"name": "Formic Acid", "formula": "HCOOH"},
    {"name": "Sulfur Hexafluoride", "formula": "SF6"},
    {"name": "Phosphorus Trichloride", "formula": "PCl3"},
    {"name": "Ethane", "formula": "C2H6"},
    {"name": "Dinitrogen Pentoxide", "formula": "N2O5"},
    {"name": "Phosphorous Acid", "formula": "H3PO3"},
    {"name": "Potassium Ferrocyanide", "formula": "K4Fe(CN)6"},
    {"name": "Xenon Difluoride", "formula": "XeF2"},
    {"name": "Diatomic Bromine", "formula": "Br2"},
    {"name": "Phenyl", "formula": "C6H5"},
    {"name": "Phosphorus Triiodide", "formula": "PI3"},
    {"name": "Peroxydisulfuric Acid", "formula": "H2S2O8"},
    {"name": "Dipotassium Phosphate", "formula": "K2HPO4"},
    {"name": "Aluminium hydroxide", "formula": "Al(OH)3"},
    {"name": "Ammonium persulfate", "formula": "(NH4)2S2O8"},
    {"name": "Sodium borate", "formula": "Na2[B4O5(OH)4]·8H2O"},
    {"name": "Chloroacetic acid", "formula": "C2H3O2Cl"},
    {"name": "Potassium acetate", "formula": "CH3CO2K"},
    {"name": "Barium oxide", "formula": "BaO"},
    {"name": "Copper(I) Oxide", "formula": "Cu2O"},
    {"name": "Copper Hydroxide", "formula": "Cu(OH)2"},
    {"name": "Tin Oxide", "formula": "SnO2"},
    {"name": "Chlorine Trifluoride", "formula": "ClF3"},
    {"name": "Ethylene", "formula": "C2H4"},
    {"name": "Acetylene", "formula": "C2H2"},
    {"name": "Chromic Oxide", "formula": "Cr2O3"},
    {"name": "Sodium bisulfate", "formula": "NaHSO4"},
    {"name": "Copper (II) chloride", "formula": "CuCl2"},
    {"name": "Mercuric chloride", "formula": "HgCl2"},
    {"name": "Tin (II) chloride", "formula": "SnCl2"},
    {"name": "Propane", "formula": "C3H8"},
    {"name": "Lead (IV) oxide", "formula": "PbO2"},
]

# “Acid Names and Anions,” Miracosta.edu, 2023. https://home.miracosta.edu/dlr/name4an.htm (accessed Dec. 23, 2023).
acids = [
    {"name": "Sulfuric acid", "formula": "H2SO4"},
    {"name": "Perchloric acid", "formula": "HClO4"},
    {"name": "Sulfurous acid", "formula": "H2SO3"},
    {"name": "Chloric acid", "formula": "HClO3"},
    {"name": "Nitric acid", "formula": "HNO3"},
    {"name": "Chlorous acid", "formula": "HClO2"},
    {"name": "Nitrous acid", "formula": "HNO2"},
    {"name": "Hypochlorous acid", "formula": "HClO"},
    {"name": "Phosphoric acid", "formula": "H3PO4"},
    {"name": "Hydrochloric acid", "formula": "HCl"},
    {"name": "Phosphorous acid", "formula": "H3PO3"},
    {"name": "Hydrobromic acid", "formula": "HBr"},
    {"name": "Carbonic acid", "formula": "H2CO3"},
    {"name": "Hydroiodic acid", "formula": "HI"},
    {"name": "Acetic acid", "formula": "HC2H3O2"},
    {"name": "Hydrofluoric acid", "formula": "HF"},
]
anions = [
    {"name": "Sulfate ion", "formula": "SO42-", "charge": -2},
    {"name": "Perchlorate ion", "formula": "ClO4-", "charge": -1},
    {"name": "Sulfite ion", "formula": "SO32-", "charge": -2},
    {"name": "Chlorate ion", "formula": "ClO3-", "charge": -1},
    {"name": "Nitrate ion", "formula": "NO3-", "charge": -1},
    {"name": "Chlorite ion", "formula": "ClO2-", "charge": -1},
    {"name": "Nitrite ion", "formula": "NO2-", "charge": -1},
    {"name": "Hypochlorite ion", "formula": "ClO-", "charge": -1},
    {"name": "Phosphate ion", "formula": "PO43-", "charge": -3},
    {"name": "Hydrogen sulfate ion", "formula": "HSO4-", "charge": -1},
    {"name": "Phosphite ion", "formula": "PO33-", "charge": -3},
    {"name": "Hydrogen carbonate ion", "formula": "HCO3-", "charge": -1},
    {"name": "Carbonate ion", "formula": "CO32-", "charge": -2},
    {"name": "Dihydrogen phosphate ion", "formula": "H2PO4-", "charge": -1},
    {"name": "Acetate ion", "formula": "C2H3O2-", "charge": -1},
    {"name": "Hydrogen phosphate ion", "formula": "HPO42-", "charge": -2},
]
i = 0
for d in acids:
    d.update(anions[i])
    i += 1

# bases = []

# organic = []